version: "3.4"
services:
  mevplus:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "10000:10000"
    environment:
      - EXTERNAL_VALIDATOR_PROXY_ADDRESS=
      - ETH1_PRIVATE_KEY=
      - BEACON_NODE_URL=
      - EXECUTION_NODE_URL=
      - LOGGER_LEVEL=debug
      - EXTRA_OPTS=
    restart: unless-stopped
    image: "mevplus.mev-plus.public.dappnode.eth:0.0.1"